AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys an ECS cluster

Parameters:
  EnvironmentName:
    Type: String
    Description: An environment name that will be prefixed to resource names

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${EnvironmentName}-Cluster"

Outputs:
  Cluster:
    Description: A reference to the ECS cluster
    Value: !Ref Cluster
