AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys an Application Load Balancer that exposes the ECS service

Parameters:
  EnvironmentName:
    Type: String
    Description: An environment name that will be prefixed to resource names

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: The VPC the Application Load Balancer should be deployed to

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The subnets the Application Load Balancer should be deployed to

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The Security Group to apply to the Application Load Balancer

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${EnvironmentName}-ALB"
      Subnets: !Ref Subnets
      SecurityGroups:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-ALB"

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DummyTargetGroup

  # We define a default target group here, as this is a mandatory Parameters
  # when creating an Application Load Balancer Listener. This is not used, instead
  # a target group is created in the service template
  DummyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-default
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP

Outputs:
  LoadBalancer:
    Description: A reference to the Application Load Balancer
    Value: !Ref LoadBalancer

  LoadBalancerUrl:
    Description: The URL of the ALB
    Value: !GetAtt LoadBalancer.DNSName

  Listener:
    Description: A reference to a port 80 listener
    Value: !Ref Listener
