name: Lint

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: requirements-dev.txt
      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: flake8 ./template.py
