name: Lint templates

on:
  workflow_call:
    inputs:
      artifact-key:
        required: true
        type: string

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download templates
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-key }}
          path: dist
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: requirements-dev.txt
      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Lint templates
        run: cfn-lint dist/*.yml
